hide_agent_reasoning = true
network_access = true

[tools]
web_search = true

[mcp_servers.github]
command = "/usr/local/bin/github-mcp-server"
args = ["stdio"]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "${GITHUB_TOKEN}"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.prompt-mcp-server]
type = "sse"
url = "http://prompt-mcp-server:3002/sse"

[mcp_servers.lsmcp]
command = "npx"
args = [
  "-y",
  "@mizchi/lsmcp",
  "--preset",
  "typescript",
  "--bin",
  "tsgo --lsp --stdio"
]